name: Graylist
author: Lee Neighoff
version: 2023.10.08
api-version: 1.20
main: com.muricagaming.graylist.Main
softdepend: []

description: "§7Simple, straightforward graylisting.§r\n§bSupport the author!§r\n§7https://ko-fi.com/leeneighoff§r"

commands:
    graylist:
      description: Command for managing Graylist.
      aliases: [glist, gl]
      permission: graylist.admin

permissions:
    graylist.*:
        description: Grants full administrative capabilities.
        default: op
        children:
            graylist.bypass: true
            graylist.admin: true